# Generated by Django 3.2.18 on 2023-03-06 18:06

import json
from pathlib import Path

from django.contrib.gis.geos import fromstr
from django.db import migrations

DATA_FILENAME = 'data.json'
def load_data(apps, schema_editor):
    Shop = apps.get_model('shops', 'Shop')
    # jsonfile = Path(__file__).parents[2] / DATA_FILENAME
    jsonfile = "/Users/denver/10bed/geodjango/shops/data.json"

    with open(str(jsonfile)) as datafile:
        objects = json.load(datafile)
        for obj in objects['elements']:
            try:
                objType = obj['type']
                if objType == 'node':
                    tags = obj['tags']
                    name = tags.get('name','no-name')
                    longitude = obj.get('lon', 0)
                    latitude = obj.get('lat', 0)
                    location = fromstr(f'POINT({longitude} {latitude})', srid=4326)
                    Shop(name=name, location = location).save()
            except KeyError:
                pass  


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        # migrations.RunPython(load_data)
    ]
